"""Python app surface: a stdlib-only CLI that turns a CSV or JSON table into a branded HTML report.

Generates ``apps/<namespace>-report/``: a PEP 621 project with no dependencies, a
``src/<namespace>_report`` package (argparse CLI, renderer, ``theme.css``), brand SVGs as
package data, a unittest suite, a README and a fictional sample table.

Identity. The distribution name, package name and console script come from the stable
``technical.namespace`` so rebranding never renames them. The firm's display name, logo
text and support link are baked into ``branding.py`` and appear in every report.

Theme. ``theme.css`` is built by the same code as the HTML guide's stylesheet
(``web_theme``) plus report-specific rules, and the renderer embeds that file verbatim so a
report is a single portable HTML file. Fonts are not packaged here: a report uses the token
font stack and falls back to system fonts.

Nothing here depends on Revit, so there is no host-verification diagnostic.
"""

from __future__ import annotations

from toolkit_engine import __version__
from toolkit_engine.adapters import RenderResult, layout, web_theme
from toolkit_engine.outputs import binary_file, text_file
from toolkit_engine.profile import Profile
from toolkit_engine.textutil import json_string, md, render_file

ADAPTER_ID = "python-app"
CSS_ROLES = (
    "color.surface.default",
    "color.surface.card",
    "color.surface.sunken",
    "color.line.subtle",
    "color.line.strong",
    "color.text.primary",
    "color.text.secondary",
    "font.display",
    "font.label",
    "font.code",
    "font-weight.display",
    "font-weight.label",
    "font-size.title",
    "font-size.small",
    "font-size.label",
    "font-size.code",
    "space.xs",
    "space.sm",
    "space.md",
    "space.lg",
    "stroke.hairline",
    "stroke.control",
    "tracking.label",
)
ASSETS = (("wordmark", "inverse"), ("symbol", "light"))


def distribution_name(namespace: str) -> str:
    return namespace + "-report"


def theme_css(profile: Profile) -> str:
    return web_theme.app_stylesheet(
        profile,
        extras_template="python_app/report.css.tmpl",
        extras_roles=CSS_ROLES,
        font_url=None,
        header="Generated by toolkit_engine {}. Managed file; the report renderer embeds it unchanged.".format(__version__),
    )


def render(profile: Profile) -> RenderResult:
    config = profile.config
    identity = config.identity
    technical = config.technical
    base = layout.python_app_dir(technical)
    package = layout.python_app_package(technical)
    name = distribution_name(technical.namespace)
    src = "{}/src/{}".format(base, package)
    result = RenderResult()
    add = result.files.append
    common = {"foundation_version": __version__}

    add(
        text_file(
            base + "/pyproject.toml",
            render_file(
                "python_app/pyproject.toml.tmpl",
                {
                    **common,
                    "name": json_string(name),
                    "name_bare": name,
                    "package": package,
                    "description": json_string("Branded HTML table reports for {}".format(identity.display_name)),
                },
            ),
            ADAPTER_ID,
        )
    )
    add(text_file(src + "/__init__.py", render_file("python_app/__init__.py.tmpl", common), ADAPTER_ID))
    add(text_file(src + "/__main__.py", render_file("python_app/__main__.py.tmpl", {"package": package}), ADAPTER_ID))
    add(
        text_file(
            src + "/branding.py",
            render_file(
                "python_app/branding.py.tmpl",
                {
                    **common,
                    "display_name": json_string(identity.display_name),
                    "short_name": json_string(identity.short_name),
                    "logo_alt": json_string(identity.logo_alt),
                    "support_url": json_string(identity.support_url),
                },
            ),
            ADAPTER_ID,
        )
    )
    add(text_file(src + "/cli.py", render_file("python_app/cli.py.tmpl", {**common, "package": package}), ADAPTER_ID))
    add(text_file(src + "/render.py", render_file("python_app/render.py.tmpl", common), ADAPTER_ID))
    add(text_file(src + "/theme.css", theme_css(profile), ADAPTER_ID))
    for slot, variant in ASSETS:
        _, content = profile.asset(slot, variant, "svg")
        add(binary_file("{}/assets/{}-{}.svg".format(src, slot, variant), content, ADAPTER_ID))

    add(
        text_file(
            base + "/tests/test_report.py",
            render_file("python_app/test_report.py.tmpl", {**common, "package": package}),
            ADAPTER_ID,
        )
    )
    add(text_file(base + "/sample.csv", render_file("python_app/sample.csv.tmpl", {}), ADAPTER_ID))
    add(
        text_file(
            base + "/README.md",
            render_file(
                "python_app/README.md.tmpl",
                {**common, "name": name, "package": package, "display_name": md(identity.display_name)},
            ),
            ADAPTER_ID,
        )
    )
    add(text_file(base + "/.gitignore", render_file("python_app/gitignore.tmpl", {}), ADAPTER_ID))
    return result
