"""Web app surface: a dependency-free TypeScript starter that runs on Node with no install step.

Generates ``apps/<namespace>-web/``: ``server.ts`` (a loopback-only static server), its
``node:test`` tests, and ``public/`` (an app shell, the generated ``theme.css``, a small
plain-JavaScript module, the brand SVGs, and packaged fonts with their licenses).

Node strips types itself, so everything TypeScript here is *erasable* syntax only. Browsers
cannot run TypeScript, so client code is plain JavaScript. ``tsc`` is never run; the
``web-app.typecheck-not-run`` diagnostic says so.

Identity. The package name comes from the stable ``technical.namespace``; display strings
(page title, wordmark alt text, support link) follow ``identity``.
"""

from __future__ import annotations

import json

from toolkit_engine import __version__
from toolkit_engine.adapters import RenderResult, layout, web_theme
from toolkit_engine.config import FontFile, FontSpec
from toolkit_engine.diagnostics import Diagnostic
from toolkit_engine.outputs import binary_file, text_file
from toolkit_engine.profile import Profile
from toolkit_engine.textutil import html, kebab, md, render_file

ADAPTER_ID = "web-app"
MINIMUM_NODE = "22.18"
CSS_ROLES = (
    "color.surface.sunken",
    "color.accent.default",
    "font-size.small",
    "space.sm",
    "space.md",
)
BRAND_FILES = (("wordmark", "inverse"), ("symbol", "light"))


def package_name(namespace: str) -> str:
    return namespace + "-web"


def _font_url(font: FontSpec, font_file: FontFile) -> str:
    """Stylesheet-relative URL: theme.css and fonts/ both sit under public/."""
    return "fonts/{}/{}".format(kebab(font.family), font_file.path.rsplit("/", 1)[-1])


def theme_css(profile: Profile) -> str:
    return web_theme.app_stylesheet(
        profile,
        extras_template="web_app/app.css.tmpl",
        extras_roles=CSS_ROLES,
        font_url=_font_url,
        header="Generated by toolkit_engine {}. Managed file.".format(__version__),
    )


def _package_json(profile: Profile) -> str:
    identity = profile.config.identity
    document = {
        "name": package_name(profile.config.technical.namespace),
        "version": "0.1.0",
        "private": True,
        "description": "Web app starter for {}".format(identity.display_name),
        "type": "module",
        "scripts": {"start": "node server.ts", "test": "node --test"},
        "engines": {"node": ">=" + MINIMUM_NODE},
    }
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def render(profile: Profile) -> RenderResult:
    config = profile.config
    identity = config.identity
    technical = config.technical
    base = layout.web_app_dir(technical)
    name = package_name(technical.namespace)
    common = {"foundation_version": __version__}
    result = RenderResult()
    add = result.files.append

    add(text_file(base + "/package.json", _package_json(profile), ADAPTER_ID))
    add(text_file(base + "/server.ts", render_file("web_app/server.ts.tmpl", common), ADAPTER_ID))
    add(text_file(base + "/test/server.test.ts", render_file("web_app/server.test.ts.tmpl", common), ADAPTER_ID))
    add(text_file(base + "/tsconfig.json", render_file("web_app/tsconfig.json.tmpl", {}), ADAPTER_ID))
    add(
        text_file(
            base + "/README.md",
            render_file("web_app/README.md.tmpl", {**common, "name": name, "display_name": md(identity.display_name)}),
            ADAPTER_ID,
        )
    )
    add(text_file(base + "/.gitignore", render_file("web_app/gitignore.tmpl", {}), ADAPTER_ID))

    add(
        text_file(
            base + "/public/index.html",
            render_file(
                "web_app/index.html.tmpl",
                {
                    **common,
                    "title": html("{} web app".format(identity.display_name)),
                    "display_name": html(identity.display_name),
                    "short_name": html(identity.short_name),
                    "logo_alt": html(identity.logo_alt),
                    "support_url": html(identity.support_url),
                },
            ),
            ADAPTER_ID,
        )
    )
    add(text_file(base + "/public/theme.css", theme_css(profile), ADAPTER_ID))
    add(text_file(base + "/public/app.js", render_file("web_app/app.js.tmpl", common), ADAPTER_ID))
    for slot, variant in BRAND_FILES:
        _, content = profile.asset(slot, variant, "svg")
        add(binary_file("{}/public/assets/{}-{}.svg".format(base, slot, variant), content, ADAPTER_ID))

    for font in config.fonts:
        folder = "{}/public/fonts/{}".format(base, kebab(font.family))
        for font_file in font.files:
            add(binary_file("{}/{}".format(folder, font_file.path.rsplit("/", 1)[-1]), profile.files[font_file.path], ADAPTER_ID))
        add(
            text_file(
                "{}/{}".format(folder, font.license_file.rsplit("/", 1)[-1]),
                profile.files[font.license_file].decode("utf-8-sig"),
                ADAPTER_ID,
            )
        )

    result.diagnostics.append(
        Diagnostic(
            "web-app.typecheck-not-run",
            "info",
            "web-app: " + base,
            "The generated TypeScript is run by Node's type stripping and is not type-checked: tsc is not installed or run.",
            "Optional: in {} run 'npm install -D typescript @types/node' and then 'npx tsc' to check types.".format(base),
        )
    )
    return result
