"""Web host surface: an HTML tool host for pyRevit (WebView2 inside a WPF window).

Generates, inside the firm extension, an IronPython 2.7 package (``lib/<namespace>_web``)
that hosts a tool's HTML in a WebView2 control, the generated assets that HTML loads
(bridge script, helper script, token-built stylesheet, packaged fonts, firm symbol), and a
read-only ``Web Tool Demo`` pushbutton: a report console that lists view counts by view type.

The WebView2 assemblies are not shipped. Every Revit from 2024 carries
``Microsoft.Web.WebView2.Core`` and ``.Wpf`` beside ``Revit.exe``; the generated host finds
them at run time in the running Revit folder and creates the WebView2 environment itself,
which avoids a defect in the Wpf assembly that Revit 2024 bundles. See FOUNDATION_SPEC 8.5.

Ported from Rob Mintzes's Rockwell Group pyRevit web library under the scoped permission
recorded in ADR 0005; see docs/product/RELEASE_RECORD.md (R06). Nothing here is live-verified
in Revit.
"""

from __future__ import annotations

from toolkit_engine import __version__
from toolkit_engine.adapters import RenderResult, layout, web_theme
from toolkit_engine.adapters.pyrevit_sample import ICON_SIZE
from toolkit_engine.config import FontFile, FontSpec
from toolkit_engine.diagnostics import Diagnostic
from toolkit_engine.outputs import OutputFile, binary_file, text_file
from toolkit_engine.png import Canvas, ring, rounded_rect
from toolkit_engine.profile import Profile
from toolkit_engine.textutil import html, kebab, md, py_string, render_file, xml, yaml_scalar
from toolkit_engine.tokens import Color

ADAPTER_ID = "web-host"
TOOLTIP = "Shows view counts by view type in an HTML report console hosted in WebView2. Read-only."

# Role tokens tool.css.tmpl reads (each becomes ``var(--<ns>-...)``).
TOOL_CSS_ROLES = (
    "color.surface.card",
    "color.surface.sunken",
    "color.text.primary",
    "color.text.secondary",
    "color.line.subtle",
    "color.line.strong",
    "color.accent.default",
    "color.focus.ring",
    "color.status.success.fg",
    "color.status.success.bg",
    "color.status.warning.fg",
    "color.status.warning.bg",
    "color.status.danger.fg",
    "color.status.danger.bg",
    "font.display",
    "font.label",
    "font.code",
    "font-weight.display",
    "font-weight.strong",
    "font-weight.label",
    "font-size.title",
    "font-size.body",
    "font-size.small",
    "font-size.label",
    "font-size.code",
    "space.sm",
    "space.md",
    "space.lg",
    "space.xl",
    "stroke.hairline",
    "stroke.control",
    "stroke.focus",
    "tracking.label",
)


def override_env_name(namespace: str) -> str:
    """Environment variable naming a firm-supplied WebView2 folder (see webview2_support)."""
    return "{}_WEBVIEW2_DIR".format(namespace.upper())


def _font_url(font: FontSpec, font_file: FontFile) -> str:
    """Stylesheet-relative URL: tool.css and fonts/ both sit in the assets folder."""
    return "fonts/{}/{}".format(kebab(font.family), font_file.path.rsplit("/", 1)[-1])


def tool_css(profile: Profile) -> str:
    """Complete stylesheet: fonts, tokens, shared button/badge rules, then the tool shell."""
    a = profile.config.appearance
    t = profile.tokens
    values = web_theme.role_values(profile, TOOL_CSS_ROLES)
    values["control_height"] = web_theme.number(t.px("size.control-height")) + "px"
    values["field_radius"] = "0" if a.button_shape == "square" else web_theme.var_ref(profile, "radius.rounded")
    parts = ["/* Generated by toolkit_engine {}. Managed file. */".format(__version__)]
    faces = web_theme.font_faces(profile, _font_url)
    if faces:
        parts.append(faces)
    parts.append(":root {\n" + web_theme.token_declarations(profile) + "\n}")
    parts.append(web_theme.component_css(profile).rstrip("\n"))
    parts.append(render_file("web_host/tool.css.tmpl", values).rstrip("\n"))
    return "\n".join(parts) + "\n"


def _identity_values(profile: Profile) -> dict[str, str]:
    technical = profile.config.technical
    tool_host, assets_host = layout.web_host_names(technical)
    return {
        "package": layout.web_host_package(technical),
        "ns": technical.namespace,
        "tool_host": tool_host,
        "assets_host": assets_host,
        "override_env": override_env_name(technical.namespace),
    }


def _package_module(profile: Profile, name: str) -> str:
    """Render one Python module (or the shell XAML) of the host package."""
    values = _identity_values(profile)
    if name == "__init__.py":
        return render_file("web_host/__init__.py.tmpl", {"package": values["package"]})
    if name == "bridge.py":
        return render_file("web_host/bridge.py.tmpl", {"ns": values["ns"]})
    if name in ("session.py", "compat.py"):
        return render_file("web_host/" + name + ".tmpl", {})
    if name == "log.py":
        return render_file("web_host/log.py.tmpl", {"ns": values["ns"]})
    if name == "webview2_support.py":
        return render_file(
            "web_host/webview2_support.py.tmpl",
            {key: values[key] for key in ("override_env", "tool_host", "assets_host")},
        )
    if name == "host.py":
        return render_file(
            "web_host/host.py.tmpl",
            {key: values[key] for key in ("package", "ns", "tool_host", "assets_host")},
        )
    raise ValueError(name)


PACKAGE_PYTHON = ("__init__.py", "bridge.py", "session.py", "log.py", "compat.py", "webview2_support.py", "host.py")


def _shell_xaml(profile: Profile) -> str:
    background: Color = profile.tokens.color("color.surface.default")
    return render_file(
        "web_host/ShellWindow.xaml.tmpl",
        {
            "foundation_version": __version__,
            "title": xml(profile.config.identity.short_name),
            "background": background.argb_hex,
        },
    )


def draw_demo_icon(profile: Profile, *, dark: bool) -> bytes:
    """A browser-window-with-bars glyph; corners follow the firm's button shape choice."""
    tokens = profile.tokens
    stroke: Color = tokens.color("color.surface.default" if dark else "color.text.primary")
    accent: Color = tokens.color("color.accent.soft" if dark else "color.accent.default")
    canvas = Canvas(ICON_SIZE, ICON_SIZE)
    x0, y0, x1, y1, width = 10.0, 16.0, 86.0, 80.0, 6.0
    shape = profile.config.appearance.button_shape
    radius = 1.5 if shape == "square" else 9.0 if shape == "pill" else min(tokens.px("radius.rounded") * 2.0, 12.0)
    outer = rounded_rect(x0, y0, x1, y1, radius)
    inner = rounded_rect(x0 + width, y0 + width, x1 - width, y1 - width, max(0.0, radius - width))
    canvas.fill(ring(outer, inner), stroke.rgba)
    # Address strip across the top, then three bars of different heights standing on a baseline.
    canvas.fill(rounded_rect(x0 + width, y0 + width, x1 - width, y0 + width + 10.0, 0.0), accent.rgba, (x0, y0, x1, y0 + 24))
    baseline = y1 - width - 7.0
    for left, top in ((24.0, 52.0), (40.0, 40.0), (56.0, 58.0)):
        canvas.fill(rounded_rect(left, top, left + 11.0, baseline, 1.5), accent.rgba, (left - 2, top - 2, left + 13, baseline + 2))
    canvas.fill(rounded_rect(21.0, baseline + 1.0, 75.0, baseline + 4.0, 1.0), (stroke.red, stroke.green, stroke.blue, 150), (19, baseline, 77, baseline + 6))
    return canvas.to_png()


def _demo_files(profile: Profile) -> list[OutputFile]:
    config = profile.config
    technical = config.technical
    identity = config.identity
    values = _identity_values(profile)
    button_dir = layout.web_tool_demo_dir(technical)
    title = layout.WEB_TOOL_DEMO_TITLE
    common = {"foundation_version": __version__}
    return [
        text_file(
            button_dir + "/bundle.yaml",
            "title: {}\ntooltip: {}\nauthor: {}\nhelp_url: {}\n".format(
                title,
                yaml_scalar(TOOLTIP),
                yaml_scalar(identity.author),
                yaml_scalar(identity.support_url),
            ),
            ADAPTER_ID,
        ),
        text_file(
            button_dir + "/script.py",
            render_file(
                "web_host/web_tool_demo_script.py.tmpl",
                {"package": values["package"], "author_literal": py_string(identity.author)},
            ),
            ADAPTER_ID,
        ),
        text_file(
            button_dir + "/tool.html",
            render_file(
                "web_host/tool.html.tmpl",
                {
                    **common,
                    "title": html(title),
                    "logo_alt": html(identity.logo_alt),
                    "tool_host": values["tool_host"],
                    "assets_host": values["assets_host"],
                },
            ),
            ADAPTER_ID,
        ),
        text_file(
            button_dir + "/tool.js",
            render_file("web_host/tool.js.tmpl", {**common, "ns": values["ns"], "title": title}),
            ADAPTER_ID,
        ),
        binary_file(button_dir + "/icon.png", draw_demo_icon(profile, dark=False), ADAPTER_ID),
        binary_file(button_dir + "/icon.dark.png", draw_demo_icon(profile, dark=True), ADAPTER_ID),
        text_file(
            layout.WEB_TOOL_DEMO_DOC,
            render_file(
                "web_host/web-tool-demo-doc.md.tmpl",
                {
                    "package": values["package"],
                    "ns": values["ns"],
                    "tool_host": values["tool_host"],
                    "assets_host": values["assets_host"],
                    "tab_display": md(technical.tab),
                    "panel_display": md(technical.sample_panel),
                    "support_url": identity.support_url,
                },
            ),
            ADAPTER_ID,
        ),
    ]


def render(profile: Profile) -> RenderResult:
    config = profile.config
    technical = config.technical
    package_dir = layout.web_host_dir(technical)
    values = _identity_values(profile)
    common = {"foundation_version": __version__}
    result = RenderResult()
    add = result.files.append

    for name in PACKAGE_PYTHON:
        add(text_file("{}/{}".format(package_dir, name), _package_module(profile, name), ADAPTER_ID))
    add(text_file(package_dir + "/ShellWindow.xaml", _shell_xaml(profile), ADAPTER_ID))

    assets = package_dir + "/assets"
    add(text_file(assets + "/bridge.js", render_file("web_host/bridge.js.tmpl", {**common, "ns": values["ns"]}), ADAPTER_ID))
    add(text_file(assets + "/tool-ui.js", render_file("web_host/tool-ui.js.tmpl", {**common, "ns": values["ns"]}), ADAPTER_ID))
    add(text_file(assets + "/tool.css", tool_css(profile), ADAPTER_ID))
    # The tool header's mark sits on the card surface, so the light variant.
    _, symbol = profile.asset("symbol", "light", "svg")
    add(binary_file(assets + "/symbol-light.svg", symbol, ADAPTER_ID))
    for font in config.fonts:
        folder = "{}/fonts/{}".format(assets, kebab(font.family))
        for font_file in font.files:
            add(binary_file("{}/{}".format(folder, font_file.path.rsplit("/", 1)[-1]), profile.files[font_file.path], ADAPTER_ID))
        add(
            text_file(
                "{}/{}".format(folder, font.license_file.rsplit("/", 1)[-1]),
                profile.files[font.license_file].decode("utf-8-sig"),
                ADAPTER_ID,
            )
        )

    result.files.extend(_demo_files(profile))

    result.diagnostics.append(
        Diagnostic(
            "web-host.not-live-verified",
            "info",
            "web-host: " + package_dir,
            "The generated web host is statically checked and its pure modules run under CPython only; it has not run inside Revit/pyRevit, and no WebView2 window has been opened.",
            "Run Web Tool Demo from the {} tab in a live session on each Revit version you support before relying on the host.".format(technical.tab),
        )
    )
    return result
