"""WPF surface: token ResourceDictionary, control styles, specimen, runner.

XAML is loose (XamlReader.Parse) with a ParserContext BaseUri at the specimen
folder, so packaged fonts and brand PNGs resolve by relative URI.
"""

from __future__ import annotations

from toolkit_engine import __version__
from toolkit_engine.adapters import RenderResult
from toolkit_engine.adapters import layout, wpf_common
from toolkit_engine.diagnostics import Diagnostic
from toolkit_engine.outputs import text_file
from toolkit_engine.profile import Profile
from toolkit_engine.textutil import pascal, render_file, xml

ADAPTER_ID = "wpf-specimen"
THEME = layout.WPF_DIR + "/Theme.xaml"


def _theme(profile: Profile) -> str:
    return wpf_common.render_theme(profile)


def _controls(profile: Profile) -> str:
    return wpf_common.render_controls(profile)


def _specimen(profile: Profile) -> str:
    config = profile.config
    ns = config.technical.namespace
    a = config.appearance

    def button_label(text: str) -> str:
        return xml(text.upper() if a.button_label_case == "uppercase" else text)

    def badge_label(text: str) -> str:
        return xml(text.upper() if a.badge_label_case == "uppercase" else text)

    return render_file(
        "wpf/Specimen.xaml.tmpl",
        {
            "ns": pascal(ns),
            "surface_default": wpf_common.resource_key(ns, "color.surface.default"),
            "surface_inverse": wpf_common.resource_key(ns, "color.surface.inverse"),
            "text_inverse": wpf_common.resource_key(ns, "color.text.inverse"),
            "title": xml("{} interface specimen".format(config.identity.display_name)),
            "display_name": xml(config.identity.display_name),
            "logo_alt": xml(config.identity.logo_alt),
            "wordmark_inverse": layout.relative(layout.WPF_DIR + "/Specimen.xaml", layout.brand_path("wordmark", "inverse", "png")),
            "symbol_light": layout.relative(layout.WPF_DIR + "/Specimen.xaml", layout.brand_path("symbol", "light", "png")),
            "label_primary": button_label("Run audit"),
            "label_secondary": button_label("Preview"),
            "label_disabled": button_label("Unavailable"),
            "label_focus": button_label("Keyboard focus"),
            "badge_info": badge_label("Info"),
            "badge_success": badge_label("Passed"),
            "badge_warning": badge_label("Review"),
            "badge_danger": badge_label("Blocked"),
            "footer": xml(
                "Generated by toolkit_engine {} for {}. Native rendering of this file is the WPF evidence; "
                "the HTML guide is checked separately.".format(__version__, config.identity.display_name)
            ),
        },
    )


def render(profile: Profile) -> RenderResult:
    result = RenderResult()
    a = profile.config.appearance
    if a.registration_marks:
        result.diagnostics.append(
            Diagnostic(
                "adapter.unsupported-choice",
                "warning",
                "wpf-specimen: appearance.decorations.registration_marks",
                "Registration marks are not rendered by the WPF adapter in this version; buttons render without them.",
                "The HTML guide renders the marks.",
            )
        )
    if "uppercase" in (a.button_label_case, a.badge_label_case):
        result.diagnostics.append(
            Diagnostic(
                "adapter.label-case-static",
                "info",
                "wpf-specimen: appearance label_case",
                "WPF has no text-transform; uppercase is applied to generated specimen labels only.",
                "Tool code must supply uppercase label text itself.",
            )
        )
    result.files.append(text_file(THEME, _theme(profile), ADAPTER_ID))
    result.files.append(text_file(layout.WPF_DIR + "/Controls.xaml", _controls(profile), ADAPTER_ID))
    result.files.append(text_file(layout.WPF_DIR + "/Specimen.xaml", _specimen(profile), ADAPTER_ID))
    result.files.append(text_file(layout.WPF_DIR + "/show-specimen.ps1", render_file("wpf/show-specimen.ps1.tmpl", {}), ADAPTER_ID))
    return result
